"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, BookOpen, Clock3, ImageIcon, Loader2, Plus, Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type Chapter = { id: string; title: string; description: string | null; order: number; videoId: string; durationSeconds: number | null; sections: unknown[]; resources: unknown[] };
type Course = { id: string; title: string; description: string | null; published: boolean; coverImageUrl: string | null; chapters: Chapter[] };

export default function CourseStudioPage() {
  const { courseId } = useParams<{ courseId: string }>(); const [course, setCourse] = useState<Course | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch(`/api/courses/${courseId}`).then(async (res) => { const json = await res.json(); if (!res.ok) throw new Error(json.error?.message || "Could not load course"); setCourse(json.data); }).catch((e) => setError(e.message)); }, [courseId]);
  if (error) return <div className="mx-auto max-w-4xl py-16 text-destructive">{error}</div>;
  if (!course) return <div className="flex justify-center py-24"><Loader2 className="animate-spin"/></div>;
  return <div className="mx-auto max-w-6xl"><Link href="/courses" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>All courses</Link><section className="mt-6 overflow-hidden rounded-2xl border bg-card"><div className="grid md:grid-cols-[280px_1fr]">{course.coverImageUrl ? <img src={course.coverImageUrl} alt="" className="h-48 w-full object-cover md:h-full"/> : <div className="flex min-h-48 items-center justify-center bg-muted text-muted-foreground"><ImageIcon className="size-8"/></div>}<div className="p-7"><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-xs font-medium ${course.published ? "bg-emerald-500/10 text-emerald-700" : "bg-amber-500/10 text-amber-700"}`}>{course.published ? "Published" : "Draft"}</span><Button asChild><Link href={`/courses/${course.id}/chapters/new`}><Plus/>Add chapter</Link></Button></div><h1 className="mt-5 text-3xl font-bold tracking-tight">{course.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{course.description || "Add a clear course description so students know what they will learn."}</p><p className="mt-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><BookOpen className="size-4"/>{course.chapters.length} chapters</p></div></div></section><section className="mt-10"><h2 className="text-xl font-semibold">Course curriculum</h2><p className="mt-1 text-sm text-muted-foreground">Each video is hosted and processed by Bunny Stream.</p><div className="mt-5 space-y-3">{course.chapters.map((chapter, index) => <Link key={chapter.id} href={`/learn/${course.id}/chapters/${chapter.id}`} className="group block"><Card className="overflow-hidden p-0 transition-colors hover:bg-muted/40"><div className="flex min-h-32 items-center gap-5"><div className="relative flex h-32 w-48 shrink-0 items-center justify-center bg-muted"><Video className="text-muted-foreground"/><span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-xs text-white">Bunny Stream</span></div><div className="min-w-0 flex-1 py-4 pr-5"><div className="flex items-center gap-2 text-xs text-muted-foreground"><span>Chapter {index + 1}</span><Clock3 className="size-4 text-amber-600"/></div><h3 className="mt-2 text-base font-semibold group-hover:text-primary">{chapter.title}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{chapter.description || "No chapter description yet."}</p><p className="mt-3 text-xs text-muted-foreground">{chapter.sections.length} timestamps · {chapter.resources.length} resources</p></div></div></Card></Link>)}{course.chapters.length === 0 && <Card className="p-10 text-center"><Video className="mx-auto size-7 text-muted-foreground"/><h3 className="mt-3 font-medium">No chapters yet</h3><p className="mt-1 text-sm text-muted-foreground">Upload your first Bunny video to start the course.</p></Card>}</div></section></div>;
}
