"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { BookOpen, Camera, Loader2, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type Profile = { email: string; fullName: string; phone: string | null; avatarUrl: string | null; roles: string[]; coursesTaught: Array<{ id: string; title: string; published: boolean; _count: { chapters: number } }> };

export default function ProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [fullName, setFullName] = useState(""); const [phone, setPhone] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function load() { const response = await fetch("/api/profile"); const json = await response.json(); if (!response.ok) throw new Error(json.error?.message || "Could not load your profile."); setProfile(json.data); setFullName(json.data.fullName); setPhone(json.data.phone || ""); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((e) => setError(e.message)); }, 0); return () => window.clearTimeout(timer); }, []);
  async function save() { setSaving(true); setError(null); try { const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName, phone }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error?.message || "Could not update profile."); setProfile((current) => current ? { ...current, ...json.data } : current); } catch (e) { setError(e instanceof Error ? e.message : "Could not update profile."); } finally { setSaving(false); } }
  async function uploadAvatar(file: File | undefined) { if (!file) return; setSaving(true); setError(null); try { const data = new FormData(); data.set("avatar", file); const response = await fetch("/api/profile", { method: "PATCH", body: data }); const json = await response.json(); if (!response.ok) throw new Error(json.error?.message || "Could not upload profile image."); setProfile((current) => current ? { ...current, ...json.data } : current); } catch (e) { setError(e instanceof Error ? e.message : "Could not upload profile image."); } finally { setSaving(false); } }
  if (!profile) return <div className="flex justify-center py-20"><Loader2 className="animate-spin" /></div>;
  const initials = profile.fullName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return <div className="mx-auto max-w-5xl space-y-6"><div><h1 className="text-2xl font-bold">Profile</h1><p className="mt-1 text-sm text-muted-foreground">Your public teacher identity and contact details.</p></div>{error && <p className="text-sm text-destructive">{error}</p>}<div className="grid gap-6 md:grid-cols-[260px_1fr]"><Card className="p-6 text-center"><div className="relative mx-auto size-24"><div className="flex size-24 items-center justify-center overflow-hidden rounded-full bg-muted text-xl font-semibold">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="Profile" className="size-full object-cover"/> : initials}</div><label className="absolute -bottom-1 -right-1 flex size-8 cursor-pointer items-center justify-center rounded-full bg-primary text-primary-foreground"><Camera className="size-4"/><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event) => void uploadAvatar(event.target.files?.[0])}/></label></div><h2 className="mt-4 font-semibold">{profile.fullName}</h2><p className="mt-1 text-sm text-muted-foreground">{profile.roles.join(" · ")}</p><p className="mt-4 text-sm text-muted-foreground">{profile.email}</p></Card><Card className="p-6"><h2 className="font-semibold">Personal details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Full name<Input value={fullName} onChange={(event) => setFullName(event.target.value)}/></label><label className="grid gap-2 text-sm font-medium">Phone<Input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="+216 …"/></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Email<Input value={profile.email} readOnly/></label></div><Button className="mt-6" onClick={() => void save()} disabled={saving}>{saving && <Loader2 className="animate-spin"/>}<Save/>Save changes</Button></Card></div><section><div className="flex items-center justify-between"><div><h2 className="font-semibold">Your courses</h2><p className="mt-1 text-sm text-muted-foreground">Published courses are visible to students who own their pack.</p></div><Button asChild size="sm"><Link href="/courses/new">Create course</Link></Button></div><div className="mt-4 space-y-2">{profile.coursesTaught.map((course) => <Card key={course.id} className="flex items-center justify-between p-4"><div className="flex items-center gap-3"><BookOpen className="size-4 text-primary"/><div><p className="font-medium">{course.title}</p><p className="text-xs text-muted-foreground">{course._count.chapters} chapters · {course.published ? "Published" : "Draft"}</p></div></div><Button asChild variant="outline" size="sm"><Link href={`/courses/${course.id}`}>Manage</Link></Button></Card>)}{profile.coursesTaught.length === 0 && <Card className="p-6 text-sm text-muted-foreground">No courses yet.</Card>}</div></section></div>;
}
