"use client";

import { useEffect, useState } from "react";
import { Check, Loader2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type Application = { id: string; fullName: string; phone: string; institution: string; qualification: string; message: string; status: string; createdAt: string; applicant: { email: string }; categories: Array<{ category: { name: string } }> };
export default function ProfessorApplicationsPage() { const [items, setItems] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = async () => { try { const res = await fetch("/api/admin/professor-applications"); const json = await res.json(); if (!res.ok) throw new Error(json.error?.message || "Could not load applications"); setItems(json.data); } catch (e) { setError(e instanceof Error ? e.message : "Could not load applications"); } finally { setLoading(false); } }; useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []); async function decide(id: string, decision: "approved" | "rejected") { const res = await fetch(`/api/admin/professor-applications/${id}/decision`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); if (!res.ok) { const json = await res.json(); setError(json.error?.message || "Could not save decision"); return; } void load(); } if (loading) return <div className="flex justify-center py-20"><Loader2 className="animate-spin"/></div>; return <div className="mx-auto max-w-5xl"><h1 className="text-2xl font-bold">Professor applications</h1><p className="mt-2 text-muted-foreground">Approval adds the professor role; rejection leaves the person as a student.</p>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}<div className="mt-8 space-y-4">{items.map((item) => <Card key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">{item.fullName}</h2><p className="text-sm text-muted-foreground">{item.applicant.email} · {item.phone}</p><p className="mt-3 text-sm">{item.categories.map(({ category }) => category.name).join(", ")}</p><p className="mt-2 text-sm text-muted-foreground">{item.institution} · {item.qualification}</p><p className="mt-3 max-w-2xl text-sm text-muted-foreground">{item.message}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-muted px-2 py-1 text-xs capitalize">{item.status}</span>{item.status === "pending" && <><Button size="sm" onClick={() => decide(item.id, "approved")}><Check/>Approve</Button><Button size="sm" variant="outline" onClick={() => decide(item.id, "rejected")}><X/>Reject</Button></>}</div></div></Card>)}{items.length === 0 && <Card className="p-8 text-center text-muted-foreground">No applications yet.</Card>}</div></div>; }
